-- IN을 길이만이 아니라 타입까지 같이 묶어줘야함
-- 안그럼 0번 그룹 길이 73,63 1번 그룹 63 있으면 63때문에 두마리까지 같이 출력됨

SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO A JOIN FISH_NAME_INFO B ON A.FISH_TYPE = B.FISH_TYPE
WHERE (A.FISH_TYPE, LENGTH) IN (
    SELECT A.FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO A JOIN FISH_NAME_INFO B ON A.FISH_TYPE = B.FISH_TYPE
    GROUP BY A.FISH_TYPE)
ORDER BY ID