# SELECT ROUND(AVG(A.LENGTH),2) AS AVERAGE_LENGTH
# FROM (
#     SELECT IFNULL(LENGTH, 10) AS LENGTH
#     FROM FISH_INFO ) A

SELECT ROUND(AVG(CASE WHEN LENGTH IS NULL THEN 10 ELSE LENGTH END),2) AS AVERAGE_LENGTH
FROM FISH_INFO