SELECT COUNT(*) AS FISH_COUNT, MAX(F.LENGTH) as MAX_LENGTH, F.FISH_TYPE as FISH_TYPE
FROM (SELECT
        ID,
        FISH_TYPE,
        CASE
            WHEN LENGTH IS NULL THEN 10
        ELSE LENGTH
        END AS LENGTH
      FROM FISH_INFO
     ) F
GROUP BY F.FISH_TYPE
HAVING AVG(F.LENGTH) >= 33
ORDER BY FISH_TYPE
