SELECT YEAR(B.SALES_DATE) as YEAR, MONTH(B.SALES_DATE) as MONTH, A.GENDER as GENDER, COUNT(DISTINCT A.USER_ID) as USERS
FROM USER_INFO A, ONLINE_SALE B
WHERE A.USER_ID = B.USER_ID and A.GENDER IS NOT NULL
<<<<<<< HEAD
GROUP BY YEAR(B.SALES_DATE), MONTH(B.SALES_DATE), A.GENDER
=======
GROUP BY YEAR(B.SALES_DATE), MONTH(B.SALES_DATE), A.GENDER

>>>>>>> e4fef825997707e7589f9a5e25724340a031e4d8
