-- 흠
-- 서울에 식당이 있어도 리뷰가 없을 수 잇음 (출력 유무 말안해줌)
-- 서울에 식당이 있다는 주소 기준이 어떻게 되는지
SELECT A.REST_ID AS REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, SCORE
FROM
(SELECT *
FROM REST_INFO
WHERE ADDRESS LIKE '서울%') A JOIN
(SELECT REST_ID, ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_REVIEW
GROUP BY REST_ID) B ON A.REST_ID = B.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC
