SELECT A.PRODUCT_ID AS PRODUCT_ID, PRODUCT_NAME, AMOUNT * PRICE AS TOTAL_SALES
FROM
(SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
FROM FOOD_ORDER
WHERE DATE_FORMAT(PRODUCE_DATE,'%Y-%m') = '2022-05'
GROUP BY PRODUCT_ID) A
JOIN FOOD_PRODUCT B ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID
