SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER AS GENDER , COUNT(DISTINCT A.USER_ID) AS USERS
FROM (
SELECT *
FROM USER_INFO
WHERE GENDER IS NOT NULL) A JOIN ONLINE_SALE B ON A.USER_ID = B.USER_ID
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER