SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES * PRICE) AS TOTAL_SALES
FROM
(SELECT BOOK_ID, SUM(SALES) AS SALES
FROM BOOK_SALES
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
GROUP BY BOOK_ID) A
LEFT JOIN
(SELECT BOOK_ID, A.AUTHOR_ID AS AUTHOR_ID, AUTHOR_NAME, CATEGORY, PRICE
FROM BOOK B JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID) B ON A.BOOK_ID = B.BOOK_ID
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC

# SELECT BOOK_ID, SUM(SALES) AS SALES
# FROM BOOK_SALES
# WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
# GROUP BY BOOK_ID