SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM (
SELECT BOOK_ID, SUM(SALES) AS SALES
FROM BOOK_SALES
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
GROUP BY BOOK_ID) A JOIN BOOK B ON A.BOOK_ID = B.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY