# SELECT MONTH(B.START_DATE) AS MONTH, B.CAR_ID AS CAR_ID, COUNT(*) AS RECORDS
# FROM
# (SELECT CAR_ID
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE YEAR(START_DATE) = 2022 AND (MONTH(START_DATE)>=8) AND (MONTH(START_DATE)<=10)
# GROUP BY CAR_ID
# HAVING COUNT(CAR_ID) >= 5
# ORDER BY CAR_ID) A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID
# GROUP BY MONTH(B.START_DATE), B.CAR_ID
# HAVING COUNT(*) > 0
# ORDER BY MONTH, CAR_ID DESC

# SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE YEAR(START_DATE) = 2022 AND MONTH(START_DATE) BETWEEN 8 AND 10
# GROUP BY CAR_ID, MONTH(START_DATE)
# HAVING CAR_ID IN (SELECT CAR_ID
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE YEAR(START_DATE) = 2022 AND (MONTH(START_DATE)>=8) AND (MONTH(START_DATE)<=10)
# GROUP BY CAR_ID
# HAVING COUNT(CAR_ID) >= 5)
# ORDER BY MONTH , CAR_ID DESC

SELECT CAR_ID, COUNT(*), SUM(CAR_ID)
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE YEAR(START_DATE) = 2022 AND (MONTH(START_DATE)>=8) AND (MONTH(START_DATE)<=10)
GROUP BY CAR_ID