SELECT A.AUTHOR_ID, A.AUTHOR_NAME, A.CATEGORY, SUM(A.PRICE * B.COUNT) AS TOTAL_SALES
FROM (
SELECT B.BOOK_ID, A.AUTHOR_ID, B.CATEGORY, A.AUTHOR_NAME, B.PRICE
FROM BOOK B JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID) A JOIN
(
SELECT BOOK_ID, SUM(SALES) AS COUNT
FROM BOOK_SALES
WHERE DATE_FORMAT(SALES_DATE,'%Y-%m') = '2022-01'
GROUP BY BOOK_ID
) B ON A.BOOK_ID = B.BOOK_ID
GROUP BY A.AUTHOR_ID, A.CATEGORY
ORDER BY A.AUTHOR_ID, A.CATEGORY DESC
