SELECT A.EMP_NO AS EMP_NO, A.EMP_NAME AS EMP_NAME,
CASE
    WHEN SUM(B.SCORE)/2 >= 96 THEN 'S'
    WHEN SUM(B.SCORE)/2 >= 90 THEN 'A'
    WHEN SUM(B.SCORE)/2 >= 80 THEN 'B'
    ELSE 'C'
END AS GRADE,
A.SAL * (CASE
    WHEN SUM(B.SCORE)/2 >= 96 THEN 0.2
    WHEN SUM(B.SCORE)/2 >= 90 THEN 0.15
    WHEN SUM(B.SCORE)/2 >= 80 THEN 0.1
    ELSE 0
END ) AS BONUS
FROM HR_EMPLOYEES A JOIN HR_GRADE B ON A.EMP_NO = B.EMP_NO
GROUP BY A.EMP_NO
ORDER BY EMP_NO