-- 노션에 기록해둠
SELECT
CASE
    WHEN GROUP_CONCAT(A.CATEGORY) LIKE"%Front End%" AND
    GROUP_CONCAT(A.NAME) LIKE"%Python%" THEN 'A'
    WHEN GROUP_CONCAT(A.NAME) LIKE"%C#%" THEN 'B'
    WHEN GROUP_CONCAT(A.CATEGORY) LIKE"%Front End%" THEN 'C'
END AS GRADE, B.ID AS ID, B.EMAIL AS EMAIL
FROM SKILLCODES A JOIN DEVELOPERS B
ON A.CODE & B.SKILL_CODE = A.CODE
GROUP BY B.ID, B.EMAIL
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID ASC
