-- 문제 설명이 모호한 것 같음.
-- 해당 코드는 물고기 이름 테이블에 모든 물고기 타입별 이름이 없을 수 있다는 전제하에 맞음

SELECT A.CNT AS FISH_COUNT, B.FISH_NAME AS FISH_NAME
FROM (
SELECT COUNT(*) AS CNT, FISH_TYPE
FROM FISH_INFO
GROUP BY FISH_TYPE ) A LEFT JOIN FISH_NAME_INFO B ON A.FISH_TYPE = B.FISH_TYPE
ORDER BY FISH_COUNT DESC